id: I15F0E032
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:58:41+00:00'
last_modified: '2022-06-10T06:36:49.660254+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3655
  title: འཇའ་ཚོན་པོད་དྲུག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CD4D:
      image_group_id: I1KG4164
      title: Volume 1 of gter chos/_'ja' tshon snying po
      total_pages: 608
      order: 1
      base_file: CD4D.txt
    99EB:
      image_group_id: I1KG4165
      title: Volume 2 of gter chos/_'ja' tshon snying po
      total_pages: 674
      order: 2
      base_file: 99EB.txt
    33D3:
      image_group_id: I1KG4166
      title: Volume 3 of gter chos/_'ja' tshon snying po
      total_pages: 396
      order: 3
      base_file: 33D3.txt
    553B:
      image_group_id: I1KG4167
      title: Volume 4 of gter chos/_'ja' tshon snying po
      total_pages: 488
      order: 4
      base_file: 553B.txt
    2E32:
      image_group_id: I1KG4168
      title: Volume 5 of gter chos/_'ja' tshon snying po
      total_pages: 712
      order: 5
      base_file: 2E32.txt
    D95F:
      image_group_id: I1KG4169
      title: Volume 6 of gter chos/_'ja' tshon snying po
      total_pages: 842
      order: 6
      base_file: D95F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
